WIP - Update SIF from ImageIndex
sylabs/oci-tools pull request #62
Opened 2024-06-21 15:08 UTC by dtrudg

WIP

2024-07-04 17:04 UTC, tri-adam requested changes
Left a few comments/questions.

My only other thought here is that it's a shame the GGCR [Cache interface](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/cache#Cache) only supports caching layers (and not manifests/configs.) Otherwise it might be a nice way to hide some of the complexity of that. Oh well!

2024-07-08 09:32 UTC, dtrudg commented on pkg/sif/update.go
> +func OptTarTempDir(d string) UpdateOpt {
:+1: not sure how I ended up with that!

2024-07-08 09:33 UTC, dtrudg commented on pkg/sif/update.go
> +}
Added OptDeleteZero. Agreed compact would be nice once the sif changes are made.

2024-07-08 14:57 UTC, tri-adam approved these changes

2024-07-08 16:03 UTC, merged