add: override artifactType
sylabs/oci-tools pull request #74
Opened 2024-07-31 17:42 UTC by wobito

2024-07-31 19:32 UTC, tri-adam requested changes
One question and suggestion about the naming of the API. Thanks!

2024-07-31 19:32 UTC, tri-adam commented on pkg/mutate/mutate.go
> +func SetConfigArtifactType(artifactType string) Mutation {
It's not the artifact type of the _config_ I don't think?

```suggestion
// SetArtifactType sets the artifact type to the specified value.
func SetArtifactType(artifactType string) Mutation {
```

2024-07-31 19:32 UTC, tri-adam commented on pkg/mutate/image.go
> +	if configArtifactType != "" && configType == "application/vnd.oci.empty.v1+json" {
What's the rationale for checking `configType == "application/vnd.oci.empty.v1+json"` here? I don't think the spec mandates that ... and it looks like the GGCR code sets it whenever an unrecognized config media type is found (https://github.com/tri-adam/go-containerregistry/blob/062c74e0d745d850e89a62512c32edd924ce9310/pkg/v1/remote/fetcher.go#L168-L170)?

2024-07-31 19:32 UTC, tri-adam commented on pkg/mutate/image.go
> +	configArtifactTypeOverride string
```suggestion
	artifactTypeOverride string
```

2024-07-31 19:32 UTC, tri-adam commented on pkg/mutate/mutate_test.go
> +			name: "SetConfigArtifactType",
```suggestion
			name: "SetArtifactType",
```

2024-07-31 22:03 UTC, wobito commented
All your suggestions I initially had, but changed it. 

Since I'm only setting the artifact type on the config I opted for the name structure. 

Let's huddle tomorrow if you have time.

2024-08-01 17:44 UTC, tri-adam commented
The code looks good, but as discussed, I think the resulting image manifest has the `artifactType` under the `config` block, rather than under the top level of the `manifest`?

For example, `pkg/mutate/testdata/TestApply/SetConfigArtifactType/manifest.golden` is currently:

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.oci.empty.v1+json",
    "size": 2,
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "artifactType": "application/vnd.sylabs.container"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 3208,
      "digest": "sha256:7050e35b49f5e348c4809f5eff915842962cb813f32062d3bbdd35c750dd7d01"
    }
  ]
}
```

But I think, according to the [spec](https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidelines-for-artifact-usage) this should be:

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "artifactType": "application/vnd.sylabs.container"
  "config": {
    "mediaType": "application/vnd.oci.empty.v1+json",
    "size": 2,
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 3208,
      "digest": "sha256:7050e35b49f5e348c4809f5eff915842962cb813f32062d3bbdd35c750dd7d01"
    }
  ]
}
```

2024-08-06 17:35 UTC, wobito commented
looks like its being worked on:
https://github.com/google/go-containerregistry/pull/1931

2026-05-28 19:18 UTC, tri-adam approved these changes

2026-05-28 19:20 UTC, merged